const produtos = [
	{
		id: 1,
		nome: "Arroz",
		setor: "Alimentos",
		preco: 20.5,
		desconto: false,
		quantidadeEstoque: 100,
		validade: "2025-01-01",
	},
	{
		id: 2,
		nome: "Feijão",
		setor: "Alimentos",
		preco: 8.99,
		desconto: true,
		descontoValor: 1.0,
		quantidadeEstoque: 120,
		validade: "2024-06-20",
	},
	{
		id: 3,
		nome: "Macarrão",
		setor: "Alimentos",
		preco: 5.49,
		desconto: false,
		quantidadeEstoque: 90,
		validade: "2025-03-11",
	},
	{
		id: 4,
		nome: "Leite",
		setor: "Laticínios",
		preco: 6.99,
		desconto: true,
		descontoValor: 0.5,
		quantidadeEstoque: 50,
		validade: "2024-05-12",
	},
	{
		id: 5,
		nome: "Queijo Mussarela",
		setor: "Laticínios",
		preco: 35.9,
		desconto: false,
		quantidadeEstoque: 60,
		validade: "2024-11-30",
	},
	{
		id: 6,
		nome: "Manteiga",
		setor: "Laticínios",
		preco: 10.99,
		desconto: true,
		descontoValor: 2.0,
		quantidadeEstoque: 40,
		validade: "2024-07-10",
	},
	{
		id: 7,
		nome: "Sabão em Pó",
		setor: "Limpeza",
		preco: 12.9,
		desconto: false,
		quantidadeEstoque: 200,
		validade: null, // Produto não perecível
	},
	{
		id: 8,
		nome: "Detergente",
		setor: "Limpeza",
		preco: 3.5,
		desconto: true,
		descontoValor: 0.3,
		quantidadeEstoque: 150,
		validade: null, // Produto não perecível
	},
	{
		id: 9,
		nome: "Desinfetante",
		setor: "Limpeza",
		preco: 7.0,
		desconto: false,
		quantidadeEstoque: 85,
		validade: null, // Produto não perecível
	},
	{
		id: 10,
		nome: "Alface",
		setor: "Hortifruti",
		preco: 3.99,
		desconto: true,
		descontoValor: 0.5,
		quantidadeEstoque: 30,
		validade: "2024-09-25",
	},
	{
		id: 11,
		nome: "Tomate",
		setor: "Hortifruti",
		preco: 8.3,
		desconto: true,
		descontoValor: 1.0,
		quantidadeEstoque: 30,
		validade: "2024-10-10",
	},
	{
		id: 12,
		nome: "Batata",
		setor: "Hortifruti",
		preco: 5.49,
		desconto: false,
		quantidadeEstoque: 100,
		validade: "2024-09-28",
	},
	{
		id: 13,
		nome: "Maçã",
		setor: "Hortifruti",
		preco: 4.99,
		desconto: true,
		descontoValor: 0.75,
		quantidadeEstoque: 80,
		validade: "2024-09-20",
	},
	{
		id: 14,
		nome: "Fralda",
		setor: "Higiene",
		preco: 45.0,
		desconto: false,
		quantidadeEstoque: 75,
		validade: null, // Produto não perecível
	},
	{
		id: 15,
		nome: "Pasta de Dente",
		setor: "Higiene",
		preco: 8.0,
		desconto: false,
		quantidadeEstoque: 120,
		validade: null, // Produto não perecível
	},
	{
		id: 16,
		nome: "Shampoo",
		setor: "Higiene",
		preco: 18.9,
		desconto: true,
		descontoValor: 3.0,
		quantidadeEstoque: 60,
		validade: null, // Produto não perecível
	},
	{
		id: 17,
		nome: "Café",
		setor: "Alimentos",
		preco: 15.5,
		desconto: true,
		descontoValor: 2.0,
		quantidadeEstoque: 80,
		validade: "2025-02-15",
	},
	{
		id: 18,
		nome: "Açúcar",
		setor: "Alimentos",
		preco: 4.99,
		desconto: false,
		quantidadeEstoque: 95,
		validade: "2025-04-01",
	},
	{
		id: 19,
		nome: "Biscoito",
		setor: "Alimentos",
		preco: 3.5,
		desconto: true,
		descontoValor: 0.4,
		quantidadeEstoque: 110,
		validade: "2024-12-15",
	},
	{
		id: 20,
		nome: "Suco de Laranja",
		setor: "Bebidas",
		preco: 9.9,
		desconto: true,
		descontoValor: 1.5,
		quantidadeEstoque: 40,
		validade: "2024-06-05",
	},
];
